name: Generate-doc

on:
    release:
        types: [published]

jobs:
    generate:
        runs-on: windows-latest
        steps:
            - name: printworkdir
              run: |
                echo $env:GITHUB_WORKSPACE
            - name: download-bve
              run: |
                Invoke-WebRequest http://bvets.net/archives/bvets6-msi.zip -o bvets6-msi.zip
                Expand-Archive bvets6-msi.zip -DestinationPath bvets6-msi
            - name: install-bve
              run: |
                Start-Process msiexec.exe -ArgumentList '/i bvets6-msi\BveTs6Setup.msi /quiet' -Wait
            - name: clone-repo
              uses: actions/checkout@v2
            - name: test
              run: |
                Get-Item *
            - name: copy-bvedll
              run: |
                mkdir $env:GITHUB_WORKSPACE\AtsEx.PluginHost\LocalReferences\BveTs
                Copy-Item "C:\Program Files\mackoy\BveTs6\Mackoy.*.dll" $env:GITHUB_WORKSPACE\AtsEx.PluginHost\LocalReferences\BveTs\
                Get-Item $env:GITHUB_WORKSPACE\AtsEx.PluginHost\LocalReferences\BveTs\*
            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.1
            - name: Build
              run : |
                    msbuild /t:restore /p:RestorePackagesConfig=true $env:GITHUB_WORKSPACE\AtsEx.sln
                    msbuild